"""Prometheus metrics for the FPL agent server.

Phase 1 ships six counters — the minimum set to verify the cache
strategy is working and to sanity-check tool / request volume after
deploy. More metrics (latency histograms, FPL API counters, Redis
hit/miss) can be added once we have real traffic.
"""

from __future__ import annotations

from prometheus_client import CONTENT_TYPE_LATEST, Counter, generate_latest

ANTHROPIC_CACHE_READ_TOKENS = Counter(
    "anthropic_cache_read_tokens_total",
    "Total input tokens served from the Anthropic prompt cache.",
)

ANTHROPIC_CACHE_WRITE_TOKENS = Counter(
    "anthropic_cache_write_tokens_total",
    "Total input tokens written to the Anthropic prompt cache.",
)

ANTHROPIC_INPUT_TOKENS = Counter(
    "anthropic_input_tokens_total",
    "Total non-cached input tokens sent to Anthropic.",
)

ANTHROPIC_OUTPUT_TOKENS = Counter(
    "anthropic_output_tokens_total",
    "Total output tokens generated by Anthropic.",
)

TOOL_CALLS = Counter(
    "tool_calls_total",
    "Count of MCP tool invocations.",
    ["tool_name", "outcome"],
)

AGENT_REQUESTS = Counter(
    "agent_requests_total",
    "Count of /agent/run requests by terminal status.",
    ["status"],
)


def render_metrics() -> tuple[bytes, str]:
    """Produce the Prometheus exposition bytes and content type."""
    return generate_latest(), CONTENT_TYPE_LATEST
